### ISSUE TITLE
Use `ServerSideApply` instead of `Replace` for Kyverno

### ISSUE THREAD

**Issue by morey-tech** [hivenetes/k8s-bootstrapper#11]
I am guessing that one of the Kyverno CRDs was too big to fit into `kubectl.kubernetes.io/last-applied-configuration` annotation that is added by `kubectl apply`, causing the Application sync to fail, leading to the use of `Replace: true`. This sync option has the potential to be destructive and might lead to resources having to be recreated, which could cause an outage. 

https://github.com/hivenetes/k8s-bootstrapper/blob/9f87f1998b1b68cb8a926e5aa02e3fdb63ce4642/bootstrap/templates/application_kyverno.yaml#L22

There's [support for `ServerSideApply`](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#server-side-apply) now, which addresses the original issue and removes the potentially destructive syncs. Try using this instead:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  ...
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
 ```
